### ISSUE TITLE
IE CSS height 100% not working on TD

### ISSUE THREAD

**Issue by qinshenxue** [qinshenxue/awesome#25]

**Comment by qinshenxue** [comment]
use 
``` css
{
    height:inherit
}
```
